import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('Native source highlighting and full-record CRUD work on desktop and mobile', async ({ page, context }) => {
  test.setTimeout(150000);
  test.skip(!process.env.FORMLOGIC_REVIEW_PASSWORD, 'Requires the local review account.');
  const login = await context.request.post('/api/auth/login', { data: { email: 'admin@formlogic.local', password: process.env.FORMLOGIC_REVIEW_PASSWORD } });
  expect(login.ok()).toBe(true);
  const headers = { 'X-CSRF-Token': (await context.cookies()).find(cookie => cookie.name === 'formlogic_csrf')!.value };
  const listed = await (await context.request.get('/api/apps')).json();
  let app = listed.apps.find((item: { slug: string }) => item.slug === 'native-source-record-review');
  if (!app) {
    const result = await context.request.post('/api/apps', { headers, data: { name: 'Source and records review', slug: 'native-source-record-review' } });
    expect(result.status()).toBe(201); app = (await result.json()).app;
  }
  const existing = await (await context.request.get(`/api/apps/${app.id}/native`)).json();
  const project = JSON.parse(await readFile('../backend/resources/native-app-starter.json', 'utf8'));
  project.files['ui/main.ui'] = '<logic>\nvar message = "Hello";\n</logic>\n<style>\n.demo { color: red; padding: 12px; }\n</style>\n<Stack><Text>{message}</Text></Stack>';
  const install = await context.request.put(`/api/apps/${app.id}/native`, { headers, data: { project, expectedVersion: existing.project?.version ?? 0 } });
  expect(install.ok(), await install.text()).toBe(true);
  const browserErrors: string[] = [];
  page.on('pageerror', error => browserErrors.push(error.message));
  await page.goto(`/apps/${app.id}/records`);
  await page.getByRole('button', { name: 'Backend code', exact: true }).click();
  const hosting = page.getByRole('dialog', { name: 'Native app hosting', exact: true });
  const colours = (label: string) => page.getByRole('region', { name: label }).locator('.view-line span').evaluateAll(spans => [...new Set(spans.filter(span => span.textContent?.trim()).map(span => getComputedStyle(span).color))]);
  const source = page.getByRole('textbox', { name: 'Private backend source', exact: true });
  await expect(source).toBeVisible();
  await expect.poll(async () => (await colours('Private backend source editor')).length).toBeGreaterThanOrEqual(3);
  await page.getByRole('region', { name: 'Private backend source editor' }).locator('.view-lines').click(); await source.press('Control+End'); await source.press('Enter');
  await page.keyboard.insertText('// Source editor browser review');
  await hosting.getByRole('tab', { name: 'screens', exact: true }).click();
  await expect.poll(async () => (await colours('Interface source editor')).length).toBeGreaterThanOrEqual(4);
  await page.screenshot({ path: '../../../ecosystem-audit/native-source-editor-desktop.png' });
  await hosting.getByRole('tab', { name: 'backend', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Private backend source editor' })).toContainText('Source editor browser review');
  await hosting.getByLabel('Private backend file', { exact: true }).selectOption('server/migrations/001.sql');
  await expect(page.getByRole('region', { name: 'Private backend source editor' })).toContainText('SQL · Read-only');
  await source.press('Control+End'); await page.keyboard.insertText('should not be saved');
  await expect.poll(async () => (await colours('Private backend source editor')).length).toBeGreaterThanOrEqual(2);
  await hosting.getByRole('button', { name: 'Publish changes', exact: true }).click();
  await expect(hosting.getByText('Installed. The app uses its private SQLite database and ZIPP backend. Existing records were preserved.', { exact: true })).toBeVisible();
  const saved = await (await context.request.get(`/api/apps/${app.id}/native`)).json();
  expect(saved.project.files['server/main.logic']).toContain('Source editor browser review');
  expect(saved.project.files['server/migrations/001.sql']).toBe(project.files['server/migrations/001.sql']);
  await hosting.getByRole('tab', { name: 'screens', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await hosting.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: '../../../ecosystem-audit/native-source-editor-mobile.png' });
  await hosting.getByRole('tab', { name: 'records', exact: true }).click();
  const browser = hosting.getByRole('region', { name: 'Database records browser' });
  await browser.getByLabel('Database table', { exact: true }).selectOption('items');
  await browser.getByRole('button', { name: 'Add record', exact: true }).click();
  const editor = page.getByRole('dialog', { name: 'Create database record', exact: true });
  const title = `CRUD review ${Date.now()} ${'Full source text '.repeat(40)}`;
  await editor.getByLabel('title', { exact: true }).fill(title);
  expect(await editor.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: '../../../ecosystem-audit/native-record-create-mobile.png' });
  await editor.getByRole('button', { name: 'Create record', exact: true }).click();
  await expect(browser.getByText('Record created.', { exact: true })).toBeVisible();
  await browser.getByRole('button', { name: 'View details', exact: true }).last().click();
  await browser.getByRole('button', { name: 'Edit record', exact: true }).click();
  const edit = page.getByRole('dialog', { name: 'Edit database record', exact: true });
  await expect(edit.getByLabel('title', { exact: true })).toHaveValue(title);
  await edit.getByLabel('title', { exact: true }).fill(title + ' Edited');
  await edit.getByRole('button', { name: 'Save record', exact: true }).click();
  await expect(browser.getByText('Record updated.', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 900 });
  await browser.getByRole('button', { name: /^View record / }).last().click();
  await browser.getByRole('button', { name: 'Edit record', exact: true }).click();
  await expect(edit.getByLabel('title', { exact: true })).toHaveValue(title + ' Edited');
  await page.screenshot({ path: '../../../ecosystem-audit/native-record-edit-desktop.png' });
  await edit.getByRole('button', { name: 'Delete record', exact: true }).click();
  const confirm = page.getByRole('dialog', { name: 'Delete this record?', exact: true });
  await confirm.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(edit).toBeVisible();
  await edit.getByRole('button', { name: 'Delete record', exact: true }).click();
  await confirm.getByRole('button', { name: 'Delete permanently', exact: true }).click();
  await expect(browser.getByText('Record deleted.', { exact: true })).toBeVisible();
  const records = await (await context.request.get(`/api/apps/${app.id}/native/records?table=items`)).json();
  expect(records.rows.some((row: { title: string }) => row.title === title + ' Edited')).toBe(false);
  await hosting.getByRole('button', { name: 'Done', exact: true }).click();
  await page.getByRole('button', { name: 'Toggle theme', exact: true }).click();
  await page.getByRole('button', { name: 'Backend code', exact: true }).click();
  await expect(hosting.locator('.monaco-editor.vs')).toBeVisible();
  await expect.poll(async () => (await colours('Private backend source editor')).length).toBeGreaterThanOrEqual(3);
  await page.screenshot({ path: '../../../ecosystem-audit/native-source-editor-light.png' });
  expect(browserErrors).toEqual([]);
});
