import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { unzipSync } from 'fflate';

test('Coffee.Dating native import, ZIPP backend and database administration', async ({ page, context }, testInfo) => {
  test.skip(!process.env.FORMLOGIC_REVIEW_PASSWORD, 'Use the isolated local review account.');
  test.setTimeout(120000);
  const app = JSON.parse(await readFile(resolve('../../../ecosystem-audit/native-coffee-app.json'), 'utf8'));
  const login = await context.request.post('/api/auth/login', { data: { email: 'admin@formlogic.local', password: process.env.FORMLOGIC_REVIEW_PASSWORD } });
  expect(login.ok()).toBe(true);
  await page.goto(`/apps/${app.id}/studio/screens`);
  await page.getByText('Hosting & app tools', { exact: true }).click();
  await page.getByRole('button', { name: 'Native app hosting', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Native app hosting', exact: true });
  await expect(dialog.getByRole('button', { name: 'Import .softn project', exact: true })).toBeEnabled();
  await dialog.getByLabel('Import native app', { exact: true }).setInputFiles(resolve('../../../coffee_dating/Coffee-Dating-Cafe-0.5.0.softn'));
  await expect(dialog.getByRole('heading', { name: 'Coffee.Dating', exact: true })).toBeVisible();
  await expect(dialog.getByRole('combobox', { name: 'Visitor access', exact: true })).toHaveValue('application');
  await dialog.getByRole('checkbox', { name: 'Use this app as the website home', exact: false }).check();
  await dialog.getByRole('button', { name: /Install app project|Publish changes/ }).click();
  await expect(dialog.getByRole('status')).toContainText('Installed.', { timeout: 60000 });
  const downloadEvent = page.waitForEvent('download');
  await dialog.getByRole('button', { name: 'Download editable project', exact: true }).click();
  const download = await downloadEvent;
  const exportedPath = testInfo.outputPath('coffee-editable.softn');
  await download.saveAs(exportedPath);
  const original = unzipSync(await readFile(resolve('../../../coffee_dating/Coffee-Dating-Cafe-0.5.0.softn')));
  const exported = unzipSync(await readFile(exportedPath));
  expect(Object.keys(exported).sort()).toEqual(Object.keys(original).sort());
  for (const path of Object.keys(original)) expect(Buffer.compare(Buffer.from(exported[path]), Buffer.from(original[path])), path).toBe(0);
  await dialog.getByRole('tab', { name: 'backend', exact: true }).click();
  await expect(dialog.getByRole('region', { name: 'Private backend source editor' }).locator('.monaco-editor')).toBeVisible();
  await dialog.getByRole('tab', { name: 'records', exact: true }).click();
  const tables = dialog.getByRole('combobox', { name: 'Database table', exact: true });
  await expect(tables.locator('option')).toHaveCount(29);
  await tables.selectOption('users');
  await expect(dialog.getByText('No records in this table yet.', { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('native-database.png'), fullPage: true });
  await page.goto(`/apps/${app.id}/studio/data`);
  const database = page.getByRole('region', { name: 'App database tables', exact: true });
  await expect(database.getByRole('button', { name: /^Browse .* records$/ })).toHaveCount(28);
  await expect(page.getByRole('navigation', { name: 'App Studio sections', exact: true })).toContainText('28 database tables');
  await expect(page.getByText('No data types yet', { exact: true })).toHaveCount(0);
  await database.getByRole('searchbox', { name: 'Search database tables', exact: true }).fill('users');
  await database.getByRole('button', { name: 'Browse users records', exact: true }).click();
  await expect(page.getByRole('dialog').getByLabel('Database table', { exact: true })).toHaveValue('users');
  await expect(page.getByRole('dialog').getByText('No records in this table yet.', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await database.getByRole('searchbox', { name: 'Search database tables', exact: true }).fill('');
  await page.screenshot({ path: '../../../ecosystem-audit/native-coffee-data-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(async () => (await database.boundingBox())?.width ?? 0).toBeGreaterThan(320);
  await page.screenshot({ path: '../../../ecosystem-audit/native-coffee-data-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto(`/app/${app.slug}`);
  const frame = page.frameLocator('iframe[title="Hosted app"]');
  await expect(frame.locator('body')).toContainText(/coffee/i, { timeout: 60000 });
  await expect(frame.getByRole('alert')).toHaveCount(0);
  await expect(frame.locator('body')).not.toContainText('SecurityError');
  const appFrame = page.frames().find(candidate => candidate.url().includes('/hosted-runtime/'))!;
  await appFrame.evaluate(() => localStorage.setItem('review-preference', 'quiet-table'));
  await expect.poll(() => page.evaluate((slug) => JSON.parse(localStorage.getItem(`formlogic:native-storage:${encodeURIComponent(slug)}`) || '{}')['review-preference'], app.slug)).toBe('quiet-table');
  await page.reload();
  await expect(frame.locator('body')).toContainText(/coffee/i, { timeout: 60000 });
  expect(await page.frames().find(candidate => candidate.url().includes('/hosted-runtime/'))!.evaluate(() => localStorage.getItem('review-preference'))).toBe('quiet-table');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: testInfo.outputPath('coffee-native-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: testInfo.outputPath('coffee-native-preview.png'), fullPage: true });
  const runtime = await context.request.get(`/api/app/${app.slug}/native`);
  expect(runtime.ok()).toBe(true);
  const runtimeData = await runtime.json();
  expect(Object.keys(runtimeData.project.client).some(path => path.startsWith('server/'))).toBe(false);
  expect(runtimeData.project.assets['assets/cafe-moment.png']).toBeTruthy();
});
