<?php

declare(strict_types=1);

namespace FormLogic\Tests\Integration;

use FormLogic\Controllers\FlowController;
use FormLogic\Database\MySQLConnection;
use FormLogic\Database\SQLiteConnection;
use FormLogic\Services\AppService;
use FormLogic\Services\AppUserService;
use FormLogic\Services\FlowService;
use FormLogic\Services\FormService;
use PHPUnit\Framework\TestCase;
use Slim\Psr7\Factory\ServerRequestFactory;
use Slim\Psr7\Response;

/**
 * GET /api/v1/script-profile — the leaf-script profile a Desktop fetches so it means the same
 * thing by a flow condition that the browser does.
 *
 * What is actually at stake in each case:
 *  - AUTH. The body is FormLogic-authored code that runs on a user's machine. It goes out behind
 *    the same flows:read gate as /app-logic, so it is never the one open route in a group where
 *    every caller already holds an owner token.
 *  - THE DOCUMENT. It is OAIY's ScriptProfile exactly. A consumer refuses the whole thing on an
 *    unknown key or a digest that does not match its preamble, so serving a wrapped or stale
 *    document means the Desktop runs NO FormLogic logic, silently falling back to whatever it
 *    would do without a profile.
 *  - CACHING. The ETag is a sha256 of the served bytes, not of the preamble alone: a change to
 *    python.files moves no preamble and would otherwise leave every Desktop on a stale copy. A
 *    Desktop polls this every five minutes; without a working 304 that is ~30 KB a poll, forever.
 *
 * Skipped without a test database (FlowController's services need one, though this route touches
 * no table).
 */
class ScriptProfileEndpointTest extends TestCase
{
    private static ?MySQLConnection $mysql = null;
    private static FlowController $ctrl;

    public static function setUpBeforeClass(): void
    {
        $root = dirname(__DIR__, 2);
        if (is_file($root . '/.env')) {
            \Dotenv\Dotenv::createImmutable($root)->safeLoad();
        }
        $config = [
            'host' => $_ENV['DB_HOST'] ?? '127.0.0.1',
            'port' => $_ENV['DB_PORT'] ?? '3306',
            'database' => $_ENV['DB_TEST_DATABASE'] ?? 'formlogic_test',
            'username' => $_ENV['DB_USERNAME'] ?? 'root',
            'password' => $_ENV['DB_PASSWORD'] ?? '',
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
        ];
        try {
            $conn = new MySQLConnection($config);
            $conn->getConnection()->query('SELECT 1');
        } catch (\Throwable $e) {
            self::markTestSkipped('No test database available: ' . $e->getMessage());
        }
        self::$mysql = $conn;
        $sqlite = new SQLiteConnection(sys_get_temp_dir() . '/formlogic-script-profile-' . bin2hex(random_bytes(4)));
        $forms = new FormService($conn, $sqlite);
        self::$ctrl = new FlowController(new FlowService($conn), new AppService($conn, $forms), new AppUserService($conn), null);
    }

    protected function setUp(): void
    {
        if (self::$mysql === null) {
            $this->markTestSkipped('No test database');
        }
    }

    /** @param array<string,string> $headers */
    private function get(?string $userId, array $headers = []): Response
    {
        $request = (new ServerRequestFactory())->createServerRequest('GET', '/api/v1/script-profile');
        if ($userId !== null) {
            $request = $request->withAttribute('userId', $userId);
        }
        foreach ($headers as $name => $value) {
            $request = $request->withHeader($name, $value);
        }
        return self::$ctrl->ownerScriptProfile($request, new Response());
    }

    private function currentEtag(): string
    {
        $digest = hash_file('sha256', FlowController::SCRIPT_PROFILE_FILE);
        $this->assertNotFalse($digest, 'the generated profile is missing — run build-script-profile.mjs');
        return '"' . $digest . '"';
    }

    public function testUnauthenticatedCallerGetsNothing(): void
    {
        $response = $this->get(null);
        $this->assertSame(401, $response->getStatusCode());
        $this->assertStringNotContainsString('preambleSha256', (string) $response->getBody());
    }

    public function testServesTheGeneratedProfileWithValidators(): void
    {
        $response = $this->get('owner-1');
        $this->assertSame(200, $response->getStatusCode());
        $this->assertSame('application/json', $response->getHeaderLine('Content-Type'));
        $this->assertSame('private, max-age=300', $response->getHeaderLine('Cache-Control'));
        $this->assertSame($this->currentEtag(), $response->getHeaderLine('ETag'));

        $body = (string) $response->getBody();
        $this->assertSame(file_get_contents(FlowController::SCRIPT_PROFILE_FILE), $body, 'the route must serve the generated bytes verbatim');

        // The bare ScriptProfile, and nothing wrapped around it: the consumer's schema is
        // additionalProperties:false, so an envelope key here is a refusal of the whole document.
        $profile = json_decode($body, true);
        $this->assertIsArray($profile);
        $this->assertSame(['v', 'preamble', 'preambleSha256', 'instructionSteps', 'python'], array_keys($profile));
        $this->assertSame(1, $profile['v']);
        $this->assertSame(hash('sha256', $profile['preamble']), $profile['preambleSha256']);
        $this->assertStringNotContainsString("\r", $body, 'the served bytes must be LF-only on every checkout');
    }

    public function testEtagCoversTheWholeDocumentNotJustThePreamble(): void
    {
        // The difference is not academic: `python.files['formlogic.py']` is half the document and
        // changes without the preamble changing. An ETag of preambleSha256 would answer 304 to
        // every Desktop after a Python-contract fix, and they would keep running the old contract.
        $response = $this->get('owner-1');
        $profile = json_decode((string) $response->getBody(), true);
        $this->assertIsArray($profile);
        $this->assertNotSame('"' . $profile['preambleSha256'] . '"', $response->getHeaderLine('ETag'));
    }

    public function testMatchingIfNoneMatchGetsABodiless304(): void
    {
        $etag = $this->currentEtag();
        $response = $this->get('owner-1', ['If-None-Match' => $etag]);
        $this->assertSame(304, $response->getStatusCode());
        $this->assertSame('', (string) $response->getBody());
        $this->assertSame($etag, $response->getHeaderLine('ETag'), 'a 304 still carries the validator');
        $this->assertSame('private, max-age=300', $response->getHeaderLine('Cache-Control'));
    }

    public function testA304IsReachedThroughEveryFormAClientMaySend(): void
    {
        $etag = $this->currentEtag();
        foreach ([$etag, 'W/' . $etag, '*', '"stale", ' . $etag] as $header) {
            $this->assertSame(304, $this->get('owner-1', ['If-None-Match' => $header])->getStatusCode(), $header);
        }
    }

    public function testAStaleOrAbsentIfNoneMatchGetsTheDocument(): void
    {
        foreach (['"0000000000000000000000000000000000000000000000000000000000000000"', ''] as $header) {
            $response = $this->get('owner-1', $header === '' ? [] : ['If-None-Match' => $header]);
            $this->assertSame(200, $response->getStatusCode());
            $this->assertStringContainsString('preambleSha256', (string) $response->getBody());
        }
    }

    public function testNoHostOnlyIdentifierCrosses(): void
    {
        // Only guest-side data is served. The driver — engine construction, the instruction-budget
        // call, the per-mode selection, the reply channel and the author-message rewrite — is host
        // code and stays in FormLogic. If one of these ever appears in the payload, FormLogic has
        // begun shipping its host to someone else's machine.
        $body = (string) $this->get('owner-1')->getBody();
        foreach ([
            'attemptPython', 'runPython', 'initPythonProject', 'setInstructionBudget', 'buildProgram',
            'EMIT_PREAMBLE', 'sanitizeOut', 'authorMessage', 'BLOCK_WRAPPERS', 'LINE_OFFSETS',
            '__emit', '__replies', '__ctxJson',
        ] as $identifier) {
            $this->assertStringNotContainsString($identifier, $body, "the served profile names the host-only identifier {$identifier}");
        }
    }
}
