/**
 * scripts/zipp-source.mjs over a fixture ZIPP repository: the source the
 * sandbox guest builds from must be the commit the installed Softn release
 * names, at its version, with LF manifests, and the guest's generated lock
 * must be ZIPP's own lock plus the guest and nothing else.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compareLocks, fetchSource, installedZipp, parseLock, seedLock, sourcePaths, tarCommitId, treeDigest, verifySource, workspaceVersion } from './zipp-source.mjs';
import { zippReleaseFixture } from '../formlogic/ui/scripts/zipp-release-fixture.mjs';

const script = resolve(dirname(fileURLToPath(import.meta.url)), 'zipp-source.mjs');
const REGISTRY = 'registry+https://github.com/rust-lang/crates.io-index';
const lockEntry = ({ name, version, source = REGISTRY, checksum = `${name}-${version}`.padEnd(64, '0').slice(0, 64), dependencies = [] }) =>
  `[[package]]\nname = "${name}"\nversion = "${version}"\n${source ? `source = "${source}"\nchecksum = "${checksum}"\n` : ''}${dependencies.length ? `dependencies = [\n${dependencies.map((d) => ` "${d}",`).join('\n')}\n]\n` : ''}`;
const lock = (entries) => `# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n${entries.map(lockEntry).join('\n')}`;
const ZIPP_PACKAGES = [
  { name: 'num-bigint', version: '0.5.1' },
  { name: 'serde_json', version: '1.0.151' },
  { name: 'zipp-cli', version: '0.0.18', source: null, dependencies: ['zipp-vm'] },
  { name: 'zipp-vm', version: '0.0.18', source: null, dependencies: ['num-bigint'] },
];
const GUEST = { name: 'formlogic-runtime-guest', version: '0.2.0', source: null, dependencies: ['serde_json', 'zipp-vm'] };
/** Stands in for `cargo update --workspace`, which rewrites the guest's lock in place. */
const cargoWriting = (entries) => ({ cargoUpdate: (guestDir) => writeFileSync(resolve(guestDir, 'Cargo.lock'), lock(entries)) });

/** A ZIPP-shaped repository: commit A is the release, commit B is a later commit the tag could be moved to. */
async function zippRepo(t, { version = '0.0.18' } = {}) {
  const dir = await mkdtemp(resolve(tmpdir(), 'formlogic-zipp-src-'));
  t.after(() => rm(dir, { recursive: true, force: true }));
  const git = (...args) => execFileSync('git', ['-C', dir, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  git('init', '-q');
  git('config', 'core.autocrlf', 'false');
  git('config', 'user.email', 'fixture@example.test');
  git('config', 'user.name', 'fixture');
  const files = {
    'Cargo.toml': `[workspace]\nresolver = "2"\nmembers = ["crates/zipp-vm", "crates/zipp-cli"]\n\n[workspace.package]\nversion = "${version}"\nedition = "2021"\n`,
    'Cargo.lock': lock(ZIPP_PACKAGES),
    'crates/zipp-vm/Cargo.toml': '[package]\nname = "zipp-vm"\nversion.workspace = true\n',
    'crates/zipp-vm/src/lib.rs': 'pub fn engine() {}\n',
  };
  for (const [path, text] of Object.entries(files)) {
    await mkdir(dirname(resolve(dir, path)), { recursive: true });
    await writeFile(resolve(dir, path), text);
  }
  git('add', '-A');
  git('commit', '-q', '-m', 'release');
  const release = git('rev-parse', 'HEAD');
  await writeFile(resolve(dir, 'crates/zipp-vm/src/lib.rs'), 'pub fn engine() { /* after the release */ }\n');
  git('commit', '-q', '-am', 'later');
  return { dir, git, release, later: git('rev-parse', 'HEAD') };
}

/** A FormLogic tree with a Softn release installed that names ZIPP `revision`. */
async function formlogic(t, { revision, version = '0.0.18', zipp } = {}) {
  const root = await mkdtemp(resolve(tmpdir(), 'formlogic-root-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await mkdir(resolve(root, '.runtime-source/softn-release'), { recursive: true });
  await mkdir(resolve(root, 'formlogic/runtime/guest'), { recursive: true });
  const record = zipp !== undefined ? zipp : zippReleaseFixture({ version, revision }).record;
  await writeFile(resolve(root, '.runtime-source/softn-release/current.json'), JSON.stringify({ tag: 'v0.0.15', zipp: record }));
  return root;
}

test('an installed Softn release before v0.0.15 names no ZIPP release to build from', async (t) => {
  const record = zippReleaseFixture({ revision: 'a'.repeat(40) }).record;
  const { release: _release, ...withoutRelease } = record;
  const empty = await mkdtemp(resolve(tmpdir(), 'formlogic-root-'));
  t.after(() => rm(empty, { recursive: true, force: true }));
  assert.throws(() => installedZipp(empty), /No Softn release is installed/);
  const noRelease = await formlogic(t, { zipp: withoutRelease });
  assert.throws(() => installedZipp(noRelease), /names no ZIPP release to build the sandbox from; it needs Softn v0\.0\.15 or later/);
  const local = await formlogic(t, { zipp: { ...record, build: 'local' } });
  assert.throws(() => installedZipp(local), /build is local, not release/);
  const cli = spawnSync(process.execPath, [script, '--root', noRelease], { encoding: 'utf8' });
  assert.equal(cli.status, 1);
  assert.match(cli.stderr, /^zipp-source: The installed Softn release v0\.0\.15 names no ZIPP release/);
  const named = await formlogic(t, { revision: 'a'.repeat(40) });
  const identity = spawnSync(process.execPath, [script, '--identity', '--root', named], { encoding: 'utf8' });
  assert.equal(identity.status, 0, identity.stderr);
  assert.equal(identity.stdout, `release=v0.0.18\nrevision=${'a'.repeat(40)}\n`, 'the lines CI appends to $GITHUB_OUTPUT');
});

test('ZIPP_SOURCE_DIR extracts the recorded commit (not the checkout\'s HEAD), verifies it and stamps it; a second run reuses it', async (t) => {
  const zipp = await zippRepo(t);
  const root = await formlogic(t, { revision: zipp.release });
  const identity = installedZipp(root);
  const logs = [];
  const stamp = fetchSource(root, identity, { sourceDir: zipp.dir, log: (line) => logs.push(line) });
  assert.equal(stamp.revision, zipp.release);
  assert.equal(stamp.version, '0.0.18');
  assert.match(stamp.cargoLockSha256, /^[0-9a-f]{64}$/);
  const { source } = sourcePaths(root);
  assert.equal(await readFile(resolve(source, 'crates/zipp-vm/src/lib.rs'), 'utf8'), 'pub fn engine() {}\n', 'the release commit, not HEAD');
  assert.deepEqual(JSON.parse(await readFile(sourcePaths(root).stamp, 'utf8')), stamp);
  assert.equal(stamp.cargoLock, 'Cargo.lock', 'which ZIPP lock seeds the guest\'s: the workspace one');
  assert.equal(stamp.treeSha256, treeDigest(source));
  fetchSource(root, identity, { sourceDir: zipp.dir, log: (line) => logs.push(line) });
  assert.match(logs.at(-1), /source already at \.runtime-source\/zipp\/src/);
  const tar = execFileSync('git', ['-C', zipp.dir, 'archive', '--format=tar', zipp.release], { maxBuffer: 1 << 26 });
  assert.equal(tarCommitId(tar), zipp.release);
  assert.equal(tarCommitId(Buffer.alloc(2048)), null);
});

test('an extracted tree edited, added to or pruned after extraction is not the release: it is refused, and fetching extracts it again', async (t) => {
  const zipp = await zippRepo(t);
  const root = await formlogic(t, { revision: zipp.release });
  const identity = installedZipp(root);
  const logs = [];
  fetchSource(root, identity, { sourceDir: zipp.dir, log: (line) => logs.push(line) });
  const { source } = sourcePaths(root);
  const engine = resolve(source, 'crates/zipp-vm/src/lib.rs');
  const changed = /is not the tree extracted for ZIPP v0\.0\.18: a file was edited, added or removed since/;
  await writeFile(engine, 'pub fn engine() { /* not ZIPP */ }\n');
  assert.throws(() => verifySource(root, identity), changed);
  fetchSource(root, identity, { sourceDir: zipp.dir, log: (line) => logs.push(line) });
  assert.match(logs.at(-1), /extracting/);
  assert.equal(await readFile(engine, 'utf8'), 'pub fn engine() {}\n', 'the release\'s file again');
  verifySource(root, identity);
  await writeFile(resolve(source, 'crates/zipp-vm/build.rs'), 'fn main() {}\n');
  assert.throws(() => verifySource(root, identity), changed, 'a file cargo would compile, added');
  await rm(resolve(source, 'crates/zipp-vm/build.rs'));
  verifySource(root, identity);
  await rm(engine);
  assert.throws(() => verifySource(root, identity), changed, 'a file removed');
});

test('a checkout whose HEAD is not the recorded commit is refused (a tag that moved)', async (t) => {
  const zipp = await zippRepo(t);
  const root = await formlogic(t, { revision: zipp.release });
  const { source } = sourcePaths(root);
  await mkdir(dirname(source), { recursive: true });
  execFileSync('git', ['-c', 'core.autocrlf=false', 'clone', '-q', zipp.dir, source], { stdio: 'pipe' });
  execFileSync('git', ['-C', source, 'config', 'core.autocrlf', 'false']);
  assert.throws(() => verifySource(root, installedZipp(root)), new RegExp(`is ZIPP commit ${zipp.later}; the installed Softn release names ZIPP v0\\.0\\.18 at ${zipp.release}\\. The tag moved`));
  execFileSync('git', ['-C', source, 'checkout', '-q', zipp.release], { stdio: 'pipe' });
  const verified = verifySource(root, installedZipp(root));
  assert.equal(verified.revision, zipp.release);
  assert.equal(verified.treeSha256, undefined, 'git proves a checkout, every time');
  // Untracked: cargo compiles a build.rs it finds whether git tracks it or not.
  await writeFile(resolve(source, 'crates/zipp-vm/build.rs'), 'fn main() {}\n');
  assert.throws(() => verifySource(root, installedZipp(root)), /has changed or extra files, so it is not ZIPP v0\.0\.18 as released:\n\?\? crates\/zipp-vm\/build\.rs/);
  await rm(resolve(source, 'crates/zipp-vm/build.rs'));
  await writeFile(resolve(source, 'crates/zipp-vm/src/lib.rs'), 'pub fn engine() { patched(); }\n');
  assert.throws(() => verifySource(root, installedZipp(root)), /has changed or extra files, so it is not ZIPP v0\.0\.18 as released/);
});

test('a workspace version other than the release\'s is refused', async (t) => {
  const zipp = await zippRepo(t, { version: '0.0.19' });
  const root = await formlogic(t, { revision: zipp.release });
  assert.throws(() => fetchSource(root, installedZipp(root), { sourceDir: zipp.dir, log: () => {} }), /ZIPP's workspace version in \.runtime-source\/zipp\/src\/Cargo\.toml is 0\.0\.19; ZIPP v0\.0\.18 is version 0\.0\.18/);
  assert.equal(workspaceVersion('[package]\nversion = "9.9.9"\n[workspace.package]\n# the release\nversion = "0.0.18" # inline\n'), '0.0.18');
  assert.equal(workspaceVersion('[workspace]\nmembers = []\n'), null);
});

test('source extracted by a git that converts line endings (core.autocrlf=true) is refused', async (t) => {
  const zipp = await zippRepo(t);
  const root = await formlogic(t, { revision: zipp.release });
  const { source } = sourcePaths(root);
  await mkdir(source, { recursive: true });
  // What a bare `git archive` does on a machine with core.autocrlf=true, and what zipp-source.mjs forces off.
  const tar = execFileSync('git', ['-C', zipp.dir, '-c', 'core.autocrlf=true', 'archive', '--format=tar', zipp.release], { maxBuffer: 1 << 26 });
  execFileSync('tar', ['-x', '-f', '-'], { cwd: source, input: tar });
  assert.match(await readFile(resolve(source, 'Cargo.toml'), 'utf8'), /\r\n/, 'the fixture really was converted');
  assert.throws(() => verifySource(root, installedZipp(root), { commit: tarCommitId(tar) }), /Cargo\.toml has CRLF line endings: the source was written with git eol conversion \(core\.autocrlf\) on/);
});

test('an extracted tree stamped for another release, or with a changed lock, is refused', async (t) => {
  const zipp = await zippRepo(t);
  const root = await formlogic(t, { revision: zipp.release });
  fetchSource(root, installedZipp(root), { sourceDir: zipp.dir, log: () => {} });
  const { source, current } = sourcePaths(root);
  await writeFile(resolve(source, 'Cargo.lock'), lock([...ZIPP_PACKAGES, { name: 'extra', version: '1.0.0' }]));
  assert.throws(() => verifySource(root, installedZipp(root)), /\.runtime-source\/zipp\/src is not the tree extracted for ZIPP v0\.0\.18/);
  await writeFile(current, JSON.stringify({ tag: 'v0.0.16', zipp: zippReleaseFixture({ version: '0.0.18', revision: zipp.later }).record }));
  assert.throws(() => verifySource(root, installedZipp(root)), new RegExp(`was extracted for ZIPP v0\\.0\\.18 at ${zipp.release}; the installed Softn release names v0\\.0\\.18 at ${zipp.later}`));
});

test('seed-lock keeps ZIPP\'s lock and adds only the guest', async (t) => {
  const zipp = await zippRepo(t);
  const root = await formlogic(t, { revision: zipp.release });
  const identity = installedZipp(root);
  fetchSource(root, identity, { sourceDir: zipp.dir, log: () => {} });
  const lockFile = resolve(sourcePaths(root).guest, 'Cargo.lock');
  // What `cargo update --workspace` does: add the guest, prune what it does not use.
  const seeded = seedLock(root, identity, cargoWriting([GUEST, ZIPP_PACKAGES[0], ZIPP_PACKAGES[1], ZIPP_PACKAGES[3]]));
  assert.equal(seeded.packages, 4);
  assert.match(seeded.cargoLockSha256, /^[0-9a-f]{64}$/);
  assert.ok(parseLock(await readFile(lockFile, 'utf8')).has('formlogic-runtime-guest 0.2.0'));
});

test('seed-lock refuses a shared package at another version, and any package ZIPP does not lock', async (t) => {
  const zipp = await zippRepo(t);
  const root = await formlogic(t, { revision: zipp.release });
  const identity = installedZipp(root);
  fetchSource(root, identity, { sourceDir: zipp.dir, log: () => {} });
  const writing = cargoWriting;
  assert.throws(() => seedLock(root, identity, writing([GUEST, ZIPP_PACKAGES[0], { name: 'serde_json', version: '1.0.152' }, ZIPP_PACKAGES[3]])),
    /not ZIPP v0\.0\.18's lock plus the guest: it moves serde_json to 1\.0\.152 \(ZIPP locks 1\.0\.151\)/);
  assert.throws(() => seedLock(root, identity, writing([GUEST, ...ZIPP_PACKAGES, { name: 'left-pad', version: '1.3.0' }])),
    /it adds left-pad 1\.3\.0, which ZIPP does not lock/);
  assert.throws(() => seedLock(root, identity, writing(ZIPP_PACKAGES)), /it does not lock formlogic-runtime-guest itself/);
  assert.deepEqual(compareLocks(lock(ZIPP_PACKAGES), lock([GUEST, { ...ZIPP_PACKAGES[1], checksum: 'e'.repeat(64) }])), [`it takes serde_json 1.0.151 from ${REGISTRY} (${'e'.repeat(64)}); ZIPP locks ${REGISTRY} (${lockEntry(ZIPP_PACKAGES[1]).match(/checksum = "([^"]+)"/)[1]})`]);
});

test('seed-lock needs verified source first', async (t) => {
  const root = await formlogic(t, { revision: 'a'.repeat(40) });
  assert.throws(() => seedLock(root, installedZipp(root), { cargoUpdate: () => assert.fail('cargo must not run') }), /holds no ZIPP source: run node scripts\/zipp-source\.mjs/);
  assert.equal(existsSync(resolve(sourcePaths(root).guest, 'Cargo.lock')), false);
});
